# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8b2c575b4e1fd030366c7ccadab4156a2c69282c0faa63d37f6083ec0a27ee72029072f846f2dc049e5d34646a3ea08dcfff56ab3163a13c6e3fd879770aec8

test:
  secret_key_base: 533eb0172875e3ecefdfd2893241fc95d4f3355d2c2f0b8c5813273ee1f51e66dabe20290781f1bfb8f9d9cc710adc7061bff01dbd8dc8d58363faa04eb21906

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
